trigger:
- azure-pipelines-dev

resources:
  containers:
  - container: Kolga
    image: devops/azure-kolga-demo:azure-pipelines-development
    endpoint: git_anders_fi

pool:
  vmImage: 'Ubuntu 18.04'

variables:
- group: kolga-vars

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    container: Kolga
    displayName: Build
    steps:
      - script: pwd && export && ./devops create_images