trigger:
- azure-pipelines-dev

pool:
  vmImage: 'Ubuntu 18.04'

variables:
- group: kolga-vars

stages:
- stage: build
  displayName: build & push Docker image
  jobs:
  - job: build_push
    displayName: build and push
    steps:
      - script: pwd && export && ./devops create_images