trigger:
- master
- azure-pipelines

pool:
  vmImage: 'Ubuntu 18.04'

variables:
- group: kolga-vars

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    container: andersinnovations/devops:azure-test
    displayName: Build
    steps:
      - script: pwd && export && source ./utils/shell_utils.sh && setup_buildkit && ./devops create_images
      - script: echo "##vso[task.setvariable variable=BUILT_DOCKER_TEST_IMAGE;isOutput=true]$(./devops 'docker_test_image')"
        name: export
- stage: Test
  displayName: execute tests
  jobs:
  - job: test
    container: andersinnovations/devops:azure-test
    displayName: execute tests
    steps:
    - script: echo $(VARIABLE1)
    - script: echo $(VARIABLE2)
    - script: echo $(stageDependencies.Build.Build.outputs['export.BUILT_DOCKER_TEST_IMAGE'])
    - script: echo $(stageDependencies.Build.outputs['Build.export.BUILT_DOCKER_TEST_IMAGE'])
    - script: export && whoami && pwd && ls -la && ./devops test_setup && make test
    variables:
      VARIABLE1: $[stageDependencies.Build.Build.outputs['export.BUILT_DOCKER_TEST_IMAGE']]
      VARIABLE2: $[stageDependencies.Build.outputs['Build.export.BUILT_DOCKER_TEST_IMAGE']]