trigger:
- master
- azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: kolga-vars

stages:
- stage: build
  displayName: build image
  jobs:
  - job: build
    container: andersinnovations/devops:azure-test
    displayName: build
    steps:
      - script: |
          pwd
          export
          source ./utils/shell_utils.sh
          setup_buildkit
          ./devops create_images
          ls -la
          cat docker_build.env
        name: build
      - script: |
          echo '##vso[task.setvariable variable=BUILT_DOCKER_TEST_IMAGE;isOutput=true]$[./devops "docker_test_image"]'
          echo VARIABLE VALUE IS $(BUILT_DOCKER_TEST_IMAGE)
        name: export
#- stage: test
#  displayName: execute tests
#  jobs:
#  - job: test
#    container: andersinnovations/devops:azure-test
#    displayName: execute tests
#    steps:
#    - task: DockerCompose@0
#      displayName: docker-compose
#      inputs:
#        action: Run a Docker Compose command
#        containerregistrytype: Container Registry
#        dockerRegistryEndpoint: anders docker registry
#        dockerComposeFile: /__w/1/s/docker-compose.yml
#        dockerComposeCommand: up
#      env:
#        BUILT_DOCKER_TEST_IMAGE: docker.anders.fi/devops/azure-kolga-demo:52e8d6693c173482c6f82e06869693f929c6f87c-development
- stage: test
  displayName: execute tests
  jobs:
  - job: test
    container: andersinnovations/devops:azure-test
    displayName: execute tests
    steps:
    - script: echo $(VARIABLE1)
      name: variable_1
    - script: echo $(VARIABLE2)
      name: variable_2
    - script: echo $(VARIABLE3)
      name: variable_3
    - script: echo $(stageDependencies.Build.Build.outputs['export.BUILT_DOCKER_TEST_IMAGE'])
    - script: echo $(stageDependencies.Build.outputs['Build.export.BUILT_DOCKER_TEST_IMAGE'])
    - script: export && whoami && pwd && ls -la && ./devops test_setup && make test
      name: run_tests
      env:
        BUILT_DOCKER_TEST_IMAGE: docker.anders.fi/devops/azure-kolga-demo:52e8d6693c173482c6f82e06869693f929c6f87c-development
    variables:
      VARIABLE1: $[stageDependencies.Build.Build.outputs['export.BUILT_DOCKER_TEST_IMAGE']]
      VARIABLE2: $[stageDependencies.Build.outputs['Build.export.BUILT_DOCKER_TEST_IMAGE']]
      VARIABLE3: $[stageDependencies.Build.outputs['Build.export.NONEXISTING']]