trigger:
- master
- azure-pipelines

pool:
  vmImage: 'Ubuntu 18.04'

variables:
- group: kolga-vars

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: ExportVars
    container: python:3.8
    displayName: ExportVars
    steps:
      - script: export
  - job: Build
    container: andersinnovations/devops:azure-test
    displayName: Build
    steps:
      - script: pwd && export && source ./utils/shell_utils.sh && setup_buildkit && ./devops create_images
- stage: Test
  displayName: execute tests
  jobs:
    - job: test
      container: andersinnovations/devops:azure-test
      displayName: execute tests
      steps:
        - script: echo PATH IS $PATH && echo THE VARIABLE IS $BUILT_DOCKER_TEST_IMAGE
          env:
            PATH: $(PATH):$(pwd)
            BUILT_DOCKER_TEST_IMAGE: $(devops "docker_test_image")
          displayName: testing environment variables
        - script: export PATH=$PATH:$(pwd) && source ./utils/shell_utils.sh && ./devops test_setup && make test