trigger:
- master
- azure-pipelines

pool:
  vmImage: 'Ubuntu 18.04'

variables:
- group: kolga-vars

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    container: andersinnovations/devops:azure-test
    displayName: Build
    steps:
      - script: pwd && export && source ./utils/shell_utils.sh && setup_buildkit && ./devops create_images
- stage: Test
  displayName: execute tests
  jobs:
    - job: test
      container: andersinnovations/devops:azure-test
      displayName: execute tests
      steps:
        - script: pwd && ls -la && devops test_setup && make test
          workingDirectory: $(Agent.BuildDirectory)
          env:
            BUILT_DOCKER_TEST_IMAGE: $(devops "docker_test_image")