[tool.black]
include = '\.pyi?$|^/devops$'
target_version = ["py38"]

[tool.poetry]
name = "kolga"
version = "3.0.0"
description = ""
authors = ["Anders Innovations <admin@anders.fi>"]

[tool.poetry.dependencies]
python = "^3.8"
kubernetes = "^11.0"
colorful = "^0.5.4"
environs = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8"
pytest-dotenv = "^0.4.0"
pytest-sugar = "^0.9.2"
black = "=19.10b0"
flake8 = "^3.7"
isort = "^4.3"
mypy = "^0.770.0"
safety = "^1.8"
sphinx = "^3.0"
recommonmark = "^0.6.0"
sphinx-rtd-theme = "^0.4.3"
docstr-coverage = "^1.0"
markdown = "^3.1"
flake8-print = "^3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
